# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atuador.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'atuador.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ratuador.proto\x12\x07\x61tuador\"\x17\n\x07\x43omando\x12\x0c\n\x04nome\x18\x01 \x01(\t\"\x1a\n\x08Resposta\x12\x0e\n\x06status\x18\x01 \x01(\t2H\n\x0e\x41tuadorService\x12\x36\n\x0f\x45xecutarComando\x12\x10.atuador.Comando\x1a\x11.atuador.Respostab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atuador_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMANDO']._serialized_start=26
  _globals['_COMANDO']._serialized_end=49
  _globals['_RESPOSTA']._serialized_start=51
  _globals['_RESPOSTA']._serialized_end=77
  _globals['_ATUADORSERVICE']._serialized_start=79
  _globals['_ATUADORSERVICE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
