# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensores.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sensores.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esensores.proto\")\n\nDadoSensor\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\x02\"\x1a\n\x08Resposta\x12\x0e\n\x06status\x18\x01 \x01(\t25\n\rSensorService\x12$\n\nEnviarDado\x12\x0b.DadoSensor\x1a\t.Respostab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensores_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DADOSENSOR']._serialized_start=18
  _globals['_DADOSENSOR']._serialized_end=59
  _globals['_RESPOSTA']._serialized_start=61
  _globals['_RESPOSTA']._serialized_end=87
  _globals['_SENSORSERVICE']._serialized_start=89
  _globals['_SENSORSERVICE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
